"""
portal_schemas/compliance.py - Pydantic models for SoilGuard Portal.

Defines schemas for soil sensors, reasoning states, hardware controls, and regional council audit logs.
"""

from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional
from pydantic import BaseModel, Field


class IrrigationAction(str, Enum):
    """Irrigation control intensity."""
    OFF = "off"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class NutrientAction(str, Enum):
    """Fertigation control levels."""
    OFF = "off"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class FanAction(str, Enum):
    """Ventilation fan control levels."""
    OFF = "off"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class SoilSensorReading(BaseModel):
    """
    Standard schema for soil telemetry readings.
    """
    sensor_id: str = Field(..., description="Unique sensor identifier (e.g. 'soil_probe_1')")
    sensor_type: str = Field(..., description="Type of sensor (e.g. 'moisture', 'temperature', 'EC', 'nitrogen', 'phosphorus', 'potassium', 'pH')")
    value: float = Field(..., description="Numerical reading value")
    unit: str = Field(..., description="Unit of measurement (e.g. '%VWC', 'C', 'dS/m', 'mg/kg', 'pH')")
    timestamp: datetime = Field(default_factory=datetime.now)


class SoilAnalysisResult(BaseModel):
    """
    LLM reasoning results of current soil parameters.
    """
    analysis_id: str = Field(..., description="Unique analysis identifier")
    status: str = Field(..., description="Overall health assessment (healthy, warning, critical)")
    moisture_trend: str = Field(..., description="Moisture trend (stable, increasing, decreasing)")
    temperature_trend: str = Field(..., description="Temperature direction (stable, increasing, decreasing)")
    ec_trend: str = Field(..., description="EC trend (stable, increasing, decreasing)")
    ph_trend: str = Field(..., description="pH direction (stable, increasing, decreasing)")
    nutrient_status: str = Field(..., description="Nutrients assessment (optimal, depleted, excessive)")
    visual_observations: Optional[str] = Field(None, description="Observations from canopy video frames")
    audio_observations: Optional[str] = Field(None, description="Acoustic detections from irrigation lines")
    timestamp: datetime = Field(default_factory=datetime.now)


class SoilOptimizationPlan(BaseModel):
    """
    Action commands generated by LLM reasoning for soil actuators.
    """
    plan_id: str = Field(..., description="Unique plan identifier")
    generated_at: datetime = Field(default_factory=datetime.now)
    
    # Actuator states
    irrigation_action: IrrigationAction = Field(..., description="Target irrigation level")
    nutrient_action: NutrientAction = Field(..., description="Target fertigation level")
    fan_action: FanAction = Field(..., description="Target ventilation level")

    # Explanations & logs
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Model confidence in the plan (0.0 - 1.0)")
    logistical_notes: Optional[str] = Field(None, description="Operational notes or warnings")
    execution_window_minutes: int = Field(..., description="Validity window for this plan")
    requires_human_review: bool = Field(default=False, description="Flag if manual sign-off is needed")

    class Config:
        json_schema_extra = {
            "example": {
                "plan_id": "opt-soil-2026-06-07-001",
                "generated_at": "2026-06-07T16:00:00Z",
                "irrigation_action": "low",
                "nutrient_action": "off",
                "fan_action": "medium",
                "confidence_score": 0.94,
                "logistical_notes": "Soil moisture near minimum threshold; activating low flow irrigation.",
                "execution_window_minutes": 30,
                "requires_human_review": False,
            }
        }


class ComplianceRecord(BaseModel):
    """
    Strict schema representing a single audit log suitable for NZ Regional Council compliance inspections.
    """
    audit_id: str = Field(..., description="Unique audit record identifier")
    timestamp: datetime = Field(default_factory=datetime.now)
    regional_council: str = Field(..., description="Name of the targeted regional council (e.g. Waikato Regional Council)")
    consent_id: str = Field(..., description="Resource consent authorization identifier (e.g. CONSENT-2026-SOIL-1992)")
    status: str = Field(..., description="Compliance status (compliant, breach_warning, breach_critical)")
    metrics: Dict[str, float] = Field(..., description="Current soil metrics (moisture, temperature, EC, pH, N-P-K)")
    actions_taken: List[str] = Field(..., description="List of physical commands executed during this interval")
    operator_notes: Optional[str] = Field(None, description="System or operator notes detailing the state")
